aliases: []
creation_timestamp: 1743361092510
current_stage: None
description: ''
last_updated_timestamp: 1743361092510
name: titanic_lr_prod
run_id: 9de2942094fb456c943b2e2ac4dab918
run_link: ''
source: models:/titanic_lr_model/1
status: READY
status_message: null
storage_location: file:///C:/Users/Dell/Downloads/Engenharia_de_Machine_Learning/python/titanic/mlflow_runs/626250116728445160/9de2942094fb456c943b2e2ac4dab918/artifacts/model
user_id: null
version: 1
