artifact_location: file:///C:/Users/Dell/Downloads/Engenharia_de_Machine_Learning/python/titanic/mlflow_runs/0
creation_time: 1743211608609
experiment_id: '0'
last_update_time: 1743211608609
lifecycle_stage: active
name: Default
