artifact_location: file:///C:/Users/Dell/Downloads/Engenharia_de_Machine_Learning/python/titanic/mlflow_runs/626250116728445160
creation_time: 1743211608634
experiment_id: '626250116728445160'
last_update_time: 1743211608634
lifecycle_stage: active
name: titanic
